FROM php:8.3-fpm

RUN apt update && apt install -y zlib1g-dev g++ git libicu-dev zip libzip-dev  \
    libfreetype-dev libjpeg62-turbo-dev libpng-dev

# php extentions
ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN install-php-extensions intl opcache pdo pdo_mysql zip exif gd apcu xdebug amqp

# install mhsendmail for MailHog integration
RUN apt update \
    && apt install -y golang-go \
    && go install github.com/mailhog/mhsendmail@latest \
    && ln ~/go/bin/mhsendmail /usr/local/bin/mhsendmail

WORKDIR /var/www/apps

# install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# install symfony cli
RUN curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | bash
RUN apt install symfony-cli

# install sudo, create a non-sudo user
ARG UID
ARG GID
ARG USERNAME=phpdev
RUN apt update \
    && apt install -y sudo \
    && addgroup --gid $GID $USERNAME \
    && adduser --uid $UID --gid $GID --disabled-password --gecos "" $USERNAME \
    && echo "$USERNAME ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# set non-sudo user user as the default user
USER $USERNAME
